Set / get supported extensions
libgit2/libgit2sharp pull request #1908
Opened 2021-09-11 18:15 UTC by jairbubbles

- C# wrapper for https://github.com/libgit2/libgit2/pull/6031

2021-09-29 07:41 UTC, jairbubbles commented
@skysb @alfonsarmi Once this is merged you'll be able to open blobless repositories by adding `GlobalSettings.SetExtensions("partialclone");` prior to opening any repositories.

Many methods can throw unexpectedly and my goal is to make it more confortable in 
 https://github.com/libgit2/libgit2sharp/pull/1909. Please let me know your thoughts and what would be the best for your use case.
 
 @bording Is there some place where doc could be added regarding the support of partially cloned repositories?

2021-10-06 06:47 UTC, skysb commented
Hi @jairbubbles 
That sounds great! Would a nuget be created so we can download and test it out, anytime soon?
In terms of #1909 I only intend to use it for blobless repositories or filtering out with patterns. Eitherways, in my use case, all I needed was to be able to instantiate the repository, as all data related to files and trees is already available in that. As long as I can read that high level data, we wouldn't need a more extensive research.

We had tried it on windows and it allowed us to get the tree data so it should be more than sufficient as of now. But Id still like to test it out to see if I'm missing any scenarios.

Cheers

2021-10-06 08:32 UTC, jairbubbles commented
Hi @skysb, I'm not maintainer so we just need to wait just a bit.

2021-11-18 11:17 UTC, skysb commented
@bording Hi, any ETC for this?

2021-11-21 18:09 UTC, bording requested changes

2021-11-21 18:09 UTC, bording commented on LibGit2Sharp/Core/NativeMethods.cs
> +        internal static extern int git_libgit2_opts(int option, string[] extensions, int len);
This P/Invoke looks problematic to me for a couple of reasons:

1. If you look at other examples of where `size_t` is being used, this is defined as `UIntPtr` in the signature. (see `git_odb_write` as example).

2. The larger issue is the string array. I know when individual strings are passed in, they always use the `StrictUtf8Marshaler`, so it seems likely that some additional marshaling is required here as well. This appears to the first instance of needing to call a function with a `char**` parameter, so there's no example to show to how to do this properly. Seems like we might need a new marshaler type to handle this.

The use of custom string marshalers was something that was in place before the start of my involvement with the project, so I don't have the historical context for why the default string marshaling isn't good enough. @ethomson Any change you can share some insight as why they are needed and what we need to do here?

2021-11-21 18:10 UTC, bording commented
@jairbubbles Please rebase the PR to resolve the conflicts!

2021-11-22 10:19 UTC, jairbubbles commented on LibGit2Sharp/Core/NativeMethods.cs
> +        internal static extern int git_libgit2_opts(int option, string[] extensions, int len);
Thx @bording I tried something with `GitStrArrayManaged.BuildFrom` which uses `StrictUtf8Marshaler`internally. Let me know if you like it better, I'm doing my best here as I don't know much about marshalling 😅

2021-11-22 13:37 UTC, jairbubbles commented
@bording There seem to be some flakiness on some jobs. I don't know if it's related to my change. See https://github.com/libgit2/libgit2sharp/runs/4285262042?check_suite_focus=true

2021-11-23 06:21 UTC, bording commented on LibGit2Sharp/Core/NativeMethods.cs
> +        internal static extern int git_libgit2_opts(int option, string[] extensions, int len);
I overlooked `GitStrArrayManaged` when I was reviewing this for the first time. What you have now does appear to be more correct. I want to test a few things to convince myself that it's correct, and then I'll do another review pass.

2021-12-29 23:32 UTC, bording approved these changes

2021-12-29 23:32 UTC, merged

2022-01-03 10:11 UTC, jairbubbles commented
Thx @bording, let me know when you publish a package with the changes.

2022-01-04 00:37 UTC, bording commented
Thanks for the PR! I've pushed 0.27.0-preview-0175 to nuget.org, which includes these changes.