Fix git_remote_connect not throwing on non-zero result
libgit2/libgit2sharp pull request #1913
Opened 2021-09-20 22:51 UTC by YuKitsune

Fixes https://github.com/libgit2/libgit2sharp/issues/1912

Couldn't really find a good spot to add tests here, open to suggestions.

2021-09-28 11:41 UTC, A-Ovchinnikov-mx requested changes

2021-09-28 11:41 UTC, A-Ovchinnikov-mx commented on LibGit2Sharp/Core/Proxy.cs
> +                throw;
Hmm, how about just wrapping `customHeaders` in a `using` block?

```cs
using (var customHeaders = new GitStrArrayManaged())
{
    int res = NativeMethods.git_remote_connect(remote, direction, ref remoteCallbacks, ref proxyOptions, ref customHeaders.Array);
    Ensure.ZeroResult(res);
}
```

2022-04-02 20:19 UTC, bording commented
Looking at this code, I'm now wondering why it only tries to dispose `customHeaders` when an exception has occurred. It seems to me that it either should always be disposing, or it never actually needs to dispose.

Regardless, this PR is an improvement, so thanks for the contribution!

2022-04-02 20:20 UTC, bording approved these changes

2022-04-02 20:20 UTC, merged

2022-04-02 20:32 UTC, bording commented
LibGit2Sharp 0.27.0-preview-0182 includes this change.